application: helenedelafage
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))
  
- url: /javascripts
  static_dir: javascripts

- url: /admin/.*
  script: helenedelafage.app
  login: admin
  
- url: /.*
  script: helenedelafage.app
  
libraries:
- name: jinja2
  version: latest